name: Docker Image Publish

on:
  push:
    branches:
      - v3.1
  pull_request:
    branches:
      - v3.1

jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建Docker镜像
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: dellear/lost-god
          dockerFile: docker/Dockerfile
          platform: linux/amd64,linux/arm64,linux/arm/v7
          tag: latest
          dockerUser: ${{ secrets.DOCKER_USERNAME }}
          dockerPassword: ${{ secrets.DOCKER_PASSWORD }}